'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
'
Namespace WSCourierService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="CourierServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class CourierService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private SrdBasedOnShippingAddressOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.BPColSysOP.My.MySettings.Default.BPColSysOP_WSCourierService_CourierService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event SrdBasedOnShippingAddressCompleted As SrdBasedOnShippingAddressCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SrdBasedOnShippingAddress", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SrdBasedOnShippingAddress(ByRef oEquipment As Equipment, ByVal dealerId As String, ByRef oAddress As Address, ByRef oAffiliateInformation As AffiliateInformation) As ResponseCourierService
            Dim results() As Object = Me.Invoke("SrdBasedOnShippingAddress", New Object() {oEquipment, dealerId, oAddress, oAffiliateInformation})
            oEquipment = CType(results(1),Equipment)
            oAddress = CType(results(2),Address)
            oAffiliateInformation = CType(results(3),AffiliateInformation)
            Return CType(results(0),ResponseCourierService)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SrdBasedOnShippingAddressAsync(ByVal oEquipment As Equipment, ByVal dealerId As String, ByVal oAddress As Address, ByVal oAffiliateInformation As AffiliateInformation)
            Me.SrdBasedOnShippingAddressAsync(oEquipment, dealerId, oAddress, oAffiliateInformation, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SrdBasedOnShippingAddressAsync(ByVal oEquipment As Equipment, ByVal dealerId As String, ByVal oAddress As Address, ByVal oAffiliateInformation As AffiliateInformation, ByVal userState As Object)
            If (Me.SrdBasedOnShippingAddressOperationCompleted Is Nothing) Then
                Me.SrdBasedOnShippingAddressOperationCompleted = AddressOf Me.OnSrdBasedOnShippingAddressOperationCompleted
            End If
            Me.InvokeAsync("SrdBasedOnShippingAddress", New Object() {oEquipment, dealerId, oAddress, oAffiliateInformation}, Me.SrdBasedOnShippingAddressOperationCompleted, userState)
        End Sub
        
        Private Sub OnSrdBasedOnShippingAddressOperationCompleted(ByVal arg As Object)
            If (Not (Me.SrdBasedOnShippingAddressCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SrdBasedOnShippingAddressCompleted(Me, New SrdBasedOnShippingAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Equipment
        
        Private equipmentTypeField As String
        
        Private equipmentMakeField As String
        
        Private equipmentModelNumberField As String
        
        Private equipmentSerialNumberField As String
        
        Private materialCodeField As String
        
        Private colorField As String
        
        Private orderActionIdField As String
        
        Private planNameField As String
        
        '''<remarks/>
        Public Property EquipmentType() As String
            Get
                Return Me.equipmentTypeField
            End Get
            Set
                Me.equipmentTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EquipmentMake() As String
            Get
                Return Me.equipmentMakeField
            End Get
            Set
                Me.equipmentMakeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EquipmentModelNumber() As String
            Get
                Return Me.equipmentModelNumberField
            End Get
            Set
                Me.equipmentModelNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EquipmentSerialNumber() As String
            Get
                Return Me.equipmentSerialNumberField
            End Get
            Set
                Me.equipmentSerialNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MaterialCode() As String
            Get
                Return Me.materialCodeField
            End Get
            Set
                Me.materialCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Color() As String
            Get
                Return Me.colorField
            End Get
            Set
                Me.colorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OrderActionId() As String
            Get
                Return Me.orderActionIdField
            End Get
            Set
                Me.orderActionIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PlanName() As String
            Get
                Return Me.planNameField
            End Get
            Set
                Me.planNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Status
        
        Private status1Field As StatusMessage
        
        Private errorCodeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Status")>  _
        Public Property Status1() As StatusMessage
            Get
                Return Me.status1Field
            End Get
            Set
                Me.status1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorCode() As String
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum StatusMessage
        
        '''<remarks/>
        Success
        
        '''<remarks/>
        Failure
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DeliveryDateInformation
        
        Private deliveryDateFromField As Date
        
        Private deliveryDateToField As Date
        
        '''<remarks/>
        Public Property DeliveryDateFrom() As Date
            Get
                Return Me.deliveryDateFromField
            End Get
            Set
                Me.deliveryDateFromField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DeliveryDateTo() As Date
            Get
                Return Me.deliveryDateToField
            End Get
            Set
                Me.deliveryDateToField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ResponseCourierService
        
        Private oEquipmentField As Equipment
        
        Private oDeliveryDateInformationField() As DeliveryDateInformation
        
        Private oStatusField As Status
        
        '''<remarks/>
        Public Property oEquipment() As Equipment
            Get
                Return Me.oEquipmentField
            End Get
            Set
                Me.oEquipmentField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property oDeliveryDateInformation() As DeliveryDateInformation()
            Get
                Return Me.oDeliveryDateInformationField
            End Get
            Set
                Me.oDeliveryDateInformationField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property oStatus() As Status
            Get
                Return Me.oStatusField
            End Get
            Set
                Me.oStatusField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class AffiliateInformation
        
        Private affiliateField As String
        
        Private marketField As String
        
        '''<remarks/>
        Public Property Affiliate() As String
            Get
                Return Me.affiliateField
            End Get
            Set
                Me.affiliateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Market() As String
            Get
                Return Me.marketField
            End Get
            Set
                Me.marketField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Address
        
        Private addressTextField As String
        
        Private cityField As String
        
        Private districtField As String
        
        Private stateField As String
        
        Private costCenterRegionField As String
        
        Private countryField As String
        
        Private areaField As String
        
        Private quarterField As String
        
        Private streetTypeField As String
        
        Private streetNameField As String
        
        Private streetPrefixField As String
        
        Private streetNumberField As String
        
        Private streetSuffixField As String
        
        Private streetIntersectionField As String
        
        Private streetIntersectionSuffixField As String
        
        Private additionalInfoField As String
        
        Private buildingTypeField As String
        
        Private buildingNumberField As String
        
        Private internalBuildingNumberField As String
        
        Private internalBuildingNumberSuffixField As String
        
        Private apartmentNumberField As String
        
        Private totalNumOfFloorsField As String
        
        Private neighborhoodField As String
        
        Private poBoxField As String
        
        Private postalCodeField As String
        
        Private socioEconomicalRankField As String
        
        '''<remarks/>
        Public Property AddressText() As String
            Get
                Return Me.addressTextField
            End Get
            Set
                Me.addressTextField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property City() As String
            Get
                Return Me.cityField
            End Get
            Set
                Me.cityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property District() As String
            Get
                Return Me.districtField
            End Get
            Set
                Me.districtField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property State() As String
            Get
                Return Me.stateField
            End Get
            Set
                Me.stateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CostCenterRegion() As String
            Get
                Return Me.costCenterRegionField
            End Get
            Set
                Me.costCenterRegionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Country() As String
            Get
                Return Me.countryField
            End Get
            Set
                Me.countryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Area() As String
            Get
                Return Me.areaField
            End Get
            Set
                Me.areaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Quarter() As String
            Get
                Return Me.quarterField
            End Get
            Set
                Me.quarterField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StreetType() As String
            Get
                Return Me.streetTypeField
            End Get
            Set
                Me.streetTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StreetName() As String
            Get
                Return Me.streetNameField
            End Get
            Set
                Me.streetNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StreetPrefix() As String
            Get
                Return Me.streetPrefixField
            End Get
            Set
                Me.streetPrefixField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StreetNumber() As String
            Get
                Return Me.streetNumberField
            End Get
            Set
                Me.streetNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StreetSuffix() As String
            Get
                Return Me.streetSuffixField
            End Get
            Set
                Me.streetSuffixField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StreetIntersection() As String
            Get
                Return Me.streetIntersectionField
            End Get
            Set
                Me.streetIntersectionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StreetIntersectionSuffix() As String
            Get
                Return Me.streetIntersectionSuffixField
            End Get
            Set
                Me.streetIntersectionSuffixField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AdditionalInfo() As String
            Get
                Return Me.additionalInfoField
            End Get
            Set
                Me.additionalInfoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BuildingType() As String
            Get
                Return Me.buildingTypeField
            End Get
            Set
                Me.buildingTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BuildingNumber() As String
            Get
                Return Me.buildingNumberField
            End Get
            Set
                Me.buildingNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InternalBuildingNumber() As String
            Get
                Return Me.internalBuildingNumberField
            End Get
            Set
                Me.internalBuildingNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InternalBuildingNumberSuffix() As String
            Get
                Return Me.internalBuildingNumberSuffixField
            End Get
            Set
                Me.internalBuildingNumberSuffixField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ApartmentNumber() As String
            Get
                Return Me.apartmentNumberField
            End Get
            Set
                Me.apartmentNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TotalNumOfFloors() As String
            Get
                Return Me.totalNumOfFloorsField
            End Get
            Set
                Me.totalNumOfFloorsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Neighborhood() As String
            Get
                Return Me.neighborhoodField
            End Get
            Set
                Me.neighborhoodField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PoBox() As String
            Get
                Return Me.poBoxField
            End Get
            Set
                Me.poBoxField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PostalCode() As String
            Get
                Return Me.postalCodeField
            End Get
            Set
                Me.postalCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SocioEconomicalRank() As String
            Get
                Return Me.socioEconomicalRankField
            End Get
            Set
                Me.socioEconomicalRankField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub SrdBasedOnShippingAddressCompletedEventHandler(ByVal sender As Object, ByVal e As SrdBasedOnShippingAddressCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SrdBasedOnShippingAddressCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResponseCourierService
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResponseCourierService)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property oEquipment() As Equipment
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),Equipment)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property oAddress() As Address
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),Address)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property oAffiliateInformation() As AffiliateInformation
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(3),AffiliateInformation)
            End Get
        End Property
    End Class
End Namespace
