'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace SAPImpresionDocumentos
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Config1Binding", [Namespace]:="urn:WS_PDF_LGWsd/Config1/document")>  _
    Partial Public Class WS_PDF_LG
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private executeZmmLgGeneraPdfOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.BPColSysOP.My.MySettings.Default.BPColSysOP_SAPImpresionDocumentos_WS_PDF_LG
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event executeZmmLgGeneraPdfCompleted As executeZmmLgGeneraPdfCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="urn:WS_PDF_LGVi", ResponseNamespace:="urn:WS_PDF_LGVi", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function executeZmmLgGeneraPdf(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal iIndicador As String, ByVal iModoTratam As Integer, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal iDocumento As String, ByVal iEjercicio As Integer) As <System.Xml.Serialization.XmlElementAttribute("Response", IsNullable:=true)> OutputLgPdf
            Dim results() As Object = Me.Invoke("executeZmmLgGeneraPdf", New Object() {iIndicador, iModoTratam, iDocumento, iEjercicio})
            Return CType(results(0),OutputLgPdf)
        End Function
        
        '''<remarks/>
        Public Overloads Sub executeZmmLgGeneraPdfAsync(ByVal iIndicador As String, ByVal iModoTratam As Integer, ByVal iDocumento As String, ByVal iEjercicio As Integer)
            Me.executeZmmLgGeneraPdfAsync(iIndicador, iModoTratam, iDocumento, iEjercicio, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub executeZmmLgGeneraPdfAsync(ByVal iIndicador As String, ByVal iModoTratam As Integer, ByVal iDocumento As String, ByVal iEjercicio As Integer, ByVal userState As Object)
            If (Me.executeZmmLgGeneraPdfOperationCompleted Is Nothing) Then
                Me.executeZmmLgGeneraPdfOperationCompleted = AddressOf Me.OnexecuteZmmLgGeneraPdfOperationCompleted
            End If
            Me.InvokeAsync("executeZmmLgGeneraPdf", New Object() {iIndicador, iModoTratam, iDocumento, iEjercicio}, Me.executeZmmLgGeneraPdfOperationCompleted, userState)
        End Sub
        
        Private Sub OnexecuteZmmLgGeneraPdfOperationCompleted(ByVal arg As Object)
            If (Not (Me.executeZmmLgGeneraPdfCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent executeZmmLgGeneraPdfCompleted(Me, New executeZmmLgGeneraPdfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:tables")>  _
    Partial Public Class OutputLgPdf
        
        Private oMensajesField() As Bapiret2
        
        Private oPdfField() As Byte
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true)>  _
        Public Property oMensajes() As Bapiret2()
            Get
                Return Me.oMensajesField
            End Get
            Set
                Me.oMensajesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", IsNullable:=true)>  _
        Public Property oPdf() As Byte()
            Get
                Return Me.oPdfField
            End Get
            Set
                Me.oPdfField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:tables")>  _
    Partial Public Class Bapiret2
        
        Private fieldField As String
        
        Private idField As String
        
        Private logMsgNoField As Integer
        
        Private logNoField As String
        
        Private messageField As String
        
        Private messageV1Field As String
        
        Private messageV2Field As String
        
        Private messageV3Field As String
        
        Private messageV4Field As String
        
        Private numberField As Integer
        
        Private parameterField As String
        
        Private rowField As Integer
        
        Private systemField As String
        
        Private typeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property field() As String
            Get
                Return Me.fieldField
            End Get
            Set
                Me.fieldField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property logMsgNo() As Integer
            Get
                Return Me.logMsgNoField
            End Get
            Set
                Me.logMsgNoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property logNo() As String
            Get
                Return Me.logNoField
            End Get
            Set
                Me.logNoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property messageV1() As String
            Get
                Return Me.messageV1Field
            End Get
            Set
                Me.messageV1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property messageV2() As String
            Get
                Return Me.messageV2Field
            End Get
            Set
                Me.messageV2Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property messageV3() As String
            Get
                Return Me.messageV3Field
            End Get
            Set
                Me.messageV3Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property messageV4() As String
            Get
                Return Me.messageV4Field
            End Get
            Set
                Me.messageV4Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property number() As Integer
            Get
                Return Me.numberField
            End Get
            Set
                Me.numberField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property parameter() As String
            Get
                Return Me.parameterField
            End Get
            Set
                Me.parameterField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property row() As Integer
            Get
                Return Me.rowField
            End Get
            Set
                Me.rowField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property system() As String
            Get
                Return Me.systemField
            End Get
            Set
                Me.systemField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property type() As String
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub executeZmmLgGeneraPdfCompletedEventHandler(ByVal sender As Object, ByVal e As executeZmmLgGeneraPdfCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class executeZmmLgGeneraPdfCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As OutputLgPdf
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),OutputLgPdf)
            End Get
        End Property
    End Class
End Namespace
