'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AdministracionBodegas

    '''<summary>
    '''frmPrincipal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmPrincipal As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''miEncabezado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents miEncabezado As Global.BPColSysOP.EncabezadoPagina

    '''<summary>
    '''cpGeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpGeneral As Global.DevExpress.Web.ASPxCallbackPanel

    '''<summary>
    '''hdIdGeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdIdGeneral As Global.DevExpress.Web.ASPxHiddenField

    '''<summary>
    '''rpInformacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpInformacion As Global.DevExpress.Web.ASPxRoundPanel

    '''<summary>
    '''gvDatos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDatos As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''gveDatos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gveDatos As Global.DevExpress.Web.ASPxGridViewExporter

    '''<summary>
    '''pcEditar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcEditar As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''flInformacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents flInformacion As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''LayoutItemNestedControlContainer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer1 As Global.DevExpress.Web.LayoutItemNestedControlContainer

    '''<summary>
    '''txtEditNombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditNombre As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''LayoutItemNestedControlContainer7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer7 As Global.DevExpress.Web.LayoutItemNestedControlContainer

    '''<summary>
    '''cmbCiudad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbCiudad As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel1 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''LayoutItemNestedControlContainer2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer2 As Global.DevExpress.Web.LayoutItemNestedControlContainer

    '''<summary>
    '''txtEditCentro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditCentro As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''LayoutItemNestedControlContainer3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer3 As Global.DevExpress.Web.LayoutItemNestedControlContainer

    '''<summary>
    '''txtEditAlmacen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditAlmacen As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''LayoutItemNestedControlContainer4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer4 As Global.DevExpress.Web.LayoutItemNestedControlContainer

    '''<summary>
    '''cmbEditUnidadNegocio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbEditUnidadNegocio As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''LayoutItemNestedControlContainer5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer5 As Global.DevExpress.Web.LayoutItemNestedControlContainer

    '''<summary>
    '''cbEditActivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbEditActivo As Global.DevExpress.Web.ASPxCheckBox

    '''<summary>
    '''lblComentario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComentario As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''LayoutItemNestedControlContainer6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer6 As Global.DevExpress.Web.LayoutItemNestedControlContainer

    '''<summary>
    '''imgEdita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgEdita As Global.DevExpress.Web.ASPxImage

    '''<summary>
    '''pcUsuarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcUsuarios As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''lbIdTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbIdTipo As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lbUsuarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbUsuarios As Global.DevExpress.Web.ASPxListBox

    '''<summary>
    '''ASPxImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxImage1 As Global.DevExpress.Web.ASPxImage

    '''<summary>
    '''cbFormatoExportar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbFormatoExportar As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''imgExpandir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgExpandir As Global.DevExpress.Web.ASPxImage

    '''<summary>
    '''imgContraer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgContraer As Global.DevExpress.Web.ASPxImage

    '''<summary>
    '''imgNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgNew As Global.DevExpress.Web.ASPxImage

    '''<summary>
    '''lblNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNew As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''LoadingPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoadingPanel As Global.DevExpress.Web.ASPxLoadingPanel
End Class
