'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CruceFisicoVsSolicitado

    '''<summary>
    '''formPrincipal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents formPrincipal As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''miEncabezado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents miEncabezado As Global.BPColSysOP.EncabezadoPagina

    '''<summary>
    '''cpGeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpGeneral As Global.DevExpress.Web.ASPxCallbackPanel

    '''<summary>
    '''callback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents callback As Global.DevExpress.Web.ASPxCallback

    '''<summary>
    '''pcConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcConsulta As Global.DevExpress.Web.ASPxPageControl

    '''<summary>
    '''ContentControl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl2 As Global.DevExpress.Web.ContentControl

    '''<summary>
    '''rpAdminCruce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpAdminCruce As Global.DevExpress.Web.ASPxRoundPanel

    '''<summary>
    '''fuArchivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuArchivo As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''lblObligatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblObligatorio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''revArchivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revArchivo As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''rfvArchivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvArchivo As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''btnUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpload As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''rdResultadoCruze control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdResultadoCruze As Global.DevExpress.Web.ASPxRoundPanel

    '''<summary>
    '''cbFormatoExportarCruzados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbFormatoExportarCruzados As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''gvDetalleCruzados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDetalleCruzados As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''gveExportadorCruzados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gveExportadorCruzados As Global.DevExpress.Web.ASPxGridViewExporter

    '''<summary>
    '''rdResultadoNoCruze control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdResultadoNoCruze As Global.DevExpress.Web.ASPxRoundPanel

    '''<summary>
    '''cbFormatoExportarNoCruzados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbFormatoExportarNoCruzados As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''gvDetalleNoCruzados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDetalleNoCruzados As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''gveExportadorNoCruzados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gveExportadorNoCruzados As Global.DevExpress.Web.ASPxGridViewExporter

    '''<summary>
    '''pcErrores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcErrores As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''pccError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pccError As Global.DevExpress.Web.PopupControlContentControl

    '''<summary>
    '''cbFormatoExportar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbFormatoExportar As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''gvErrores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvErrores As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''gveErrores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gveErrores As Global.DevExpress.Web.ASPxGridViewExporter

    '''<summary>
    '''ContentControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl1 As Global.DevExpress.Web.ContentControl

    '''<summary>
    '''rpAdministradorConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpAdministradorConsulta As Global.DevExpress.Web.ASPxRoundPanel

    '''<summary>
    '''txtSerial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSerial As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''cmbEstado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbEstado As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''deFechaInicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents deFechaInicio As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''deFechaFin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents deFechaFin As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''btnBuscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBuscar As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btnLimpiar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLimpiar As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''rpConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpConsulta As Global.DevExpress.Web.ASPxRoundPanel

    '''<summary>
    '''cbFormatoExportarConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbFormatoExportarConsulta As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''gvConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvConsulta As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''gveExportadorConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gveExportadorConsulta As Global.DevExpress.Web.ASPxGridViewExporter

    '''<summary>
    '''LoadingPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoadingPanel As Global.DevExpress.Web.ASPxLoadingPanel
End Class
