'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PoolRadicacionBanco

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''miEncabezado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents miEncabezado As Global.BPColSysOP.EncabezadoPagina

    '''<summary>
    '''txtRecepcionRad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRecepcionRad As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''cpGeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpGeneral As Global.DevExpress.Web.ASPxCallbackPanel

    '''<summary>
    '''gvDatos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDatos As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''txtCedulaRadiacado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCedulaRadiacado As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtCampaniaEstrategia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCampaniaEstrategia As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hdfIdRadicado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfIdRadicado As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfContenidoTablaResultado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfContenidoTablaResultado As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfUsuarioSesion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfUsuarioSesion As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfCausalesBanco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCausalesBanco As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''fuArchivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuArchivo As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''revArchivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revArchivo As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''rfvArchivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvArchivo As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''btnAgregarSoportes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAgregarSoportes As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvSoporte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSoporte As Global.System.Web.UI.WebControls.GridView
End Class
