'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RegistrarServicioTipoVentaEDUCLIC

    '''<summary>
    '''formPrincipal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents formPrincipal As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''miEncabezado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents miEncabezado As Global.BPColSysOP.EncabezadoPagina

    '''<summary>
    '''cbCuposEntrega control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbCuposEntrega As Global.DevExpress.Web.ASPxCallback

    '''<summary>
    '''cbPrincipal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbPrincipal As Global.DevExpress.Web.ASPxCallback

    '''<summary>
    '''rpRegistros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpRegistros As Global.DevExpress.Web.ASPxRoundPanel

    '''<summary>
    '''cmbCiudadEntrega control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbCiudadEntrega As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''cmbEstablecimientos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbEstablecimientos As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''cmbCompania control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbCompania As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''cmbPlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbPlan As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''cmbEquipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbEquipo As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''cbRequerido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbRequerido As Global.DevExpress.Web.ASPxCheckBox

    '''<summary>
    '''txtIdentificacionCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdentificacionCliente As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''lblValorEquipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblValorEquipo As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''cmbTipoCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTipoCliente As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''lblValorARecaudar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblValorARecaudar As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtNombresCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNombresCliente As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtBarrio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBarrio As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''asDireccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents asDireccion As Global.BPColSysOP.SelectorDireccion

    '''<summary>
    '''rfvasDireccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvasDireccion As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''memoObservacionDireccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents memoObservacionDireccion As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''txtTelefonoMovil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelefonoMovil As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtTelefonoFijo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelefonoFijo As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''cmbTipoIdentificacionNino control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTipoIdentificacionNino As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''txtIdentificacionNino control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdentificacionNino As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''cmbFormaPago control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbFormaPago As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''cmbClausula control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbClausula As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''cmbRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbRegion As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''cmbJornada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbJornada As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''dateFechaAgenda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dateFechaAgenda As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''hfFechasNoDisponibles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfFechasNoDisponibles As Global.DevExpress.Web.ASPxHiddenField

    '''<summary>
    '''memoObservaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents memoObservaciones As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''btnGuardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGuardar As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btnLimpiaCampos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLimpiaCampos As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''pcAutorizar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcAutorizar As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''cmbClaseSIM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbClaseSIM As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''rpAutenticacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpAutenticacion As Global.DevExpress.Web.ASPxRoundPanel

    '''<summary>
    '''txtUsuarioAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUsuarioAdmin As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtClaveAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClaveAdmin As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''btnAutorizar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAutorizar As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''LoadingPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoadingPanel As Global.DevExpress.Web.ASPxLoadingPanel
End Class
